### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tsumuri1017** [Yukkku/To-tsumuri3#1]

**Comment by Yukkku** [comment]
nekonyonさんの現垢ってわかりますか。

**Comment by tsumuri3** [comment]
namiuzura
pyon4
この2つは絶対なはずです

**Comment by Yukkku** [comment]
その2つは最近活動していないようですね。活動していないので実行してもらえる確率は低いと思います。同一人物ならなおさら実行してもらえないかもしれません。

**Comment by tsumuri3** [comment]
あ、察しました。
何かを見せたりですか...

**Comment by tsumuri3** [comment]
ちなみに、
何を見せていたんですか？

**Comment by Yukkku** [comment]
とあるJavascriptのコードです。それを実行してもらうことでIPなどのデータが分かります。

**Comment by tsumuri3** [comment]
じゃあ実行するのは相手なんですね。

**Comment by tsumuri3** [comment]
では、相手にはどうやって実行させるつもりでしたか？
(ブックマークレッドとかですかね...)

**Comment by itta611** [comment]
相手に自分でJavascriptを実行させる"Self XSS"をやろうとしているのですね。
それはあまりよろしくないかと、、
